// AQROOT DEMO -- AS-BUILT HARDWARE DEFINITION.  DO NOT EDIT BY HAND.
//
// Generated by hardware/demo/manufacturing/gen_firmware_hw_map.py
// from aqroot-Beta-v2.kicad_pcb
// board_sha256 40e65ac99bffb1764fc6cc09a7898fedbb802893af22ee996f01034a03a9afcf
//
// Every pin, bit and address below was read out of that board file.  Direction,
// active level, safe boot latch, interrupt mask and internal-pull policy are
// engineering intent and live in the generator, where each row is checked
// against the copper before it is emitted:  an OUTPUT's safe latch must equal
// the level its external pull already holds, and an UNMASKED INPUT must have a
// defined idle level.
//
// checks/firmware_hw_map_contract.py re-runs the generator and FAILS if this
// file is not byte-identical to what the board says today.
#pragma once

#define AQROOT_DEMO_BOARD_SHA256 "40e65ac99bffb1764fc6cc09a7898fedbb802893af22ee996f01034a03a9afcf"

// ====================================================================================
// ESP32-S3-WROOM-1-N16R8 (U1) -- GPIO by role
// ====================================================================================

// U1.4  IO4   /SPI_B_SCK
//   shared SPI-B: CC1101 + SX1262 + ST25R3916
#define AQROOT_PIN_SPI_B_SCK          4

// U1.5  IO5   /SPI_B_MOSI
//   shared SPI-B
#define AQROOT_PIN_SPI_B_MOSI         5

// U1.6  IO6   /SPI_B_MISO
//   shared SPI-B
#define AQROOT_PIN_SPI_B_MISO         6

// U1.7  IO7   /CC1101_CS_N
//   433 MHz E07 chip select, active low
#define AQROOT_PIN_CC1101_CS_N        7

// U1.8  IO15  /CC1101_GDO0
//   433 MHz packet/sync interrupt; GDO2 is NOT wired on this board
#define AQROOT_PIN_CC1101_GDO0        15

// U1.9  IO16  /IR_TX_GPIO16
//   drives Q1 gate through R22 100R; R23 100k gate pull-down; ACTIVE HIGH
#define AQROOT_PIN_IR_TX              16

// U1.10 IO17  /SX1262_CS_N
//   915 MHz E22 chip select, active low
#define AQROOT_PIN_SX1262_CS_N        17

// U1.11 IO18  /NFC_IRQ
//   ST25R3916 IRQ, push-pull, ACTIVE HIGH; no external pull
#define AQROOT_PIN_NFC_IRQ            18

// U1.12 IO8   /SX1262_BUSY
//   SX1262 BUSY; must be low before any command
#define AQROOT_PIN_SX1262_BUSY        8

// U1.15 IO3   /BMI270_INT1_STRAP
//   BMI270 INT1, push-pull from the IMU, ACTIVE HIGH
//   STRAP: GPIO3 is the JTAG-source strap. R110 10k to GND holds it low through reset; R18
//   220R isolates the BMI270 INT1 driver so the IMU cannot fight the strap at boot
#define AQROOT_PIN_BMI270_INT1        3

// U1.16 IO46  /02_MCU_CORE/DISP_BL_CTL_STRAP
//   U17 TPS61169 WLED boost enable / PWM brightness through R109 0R
//   STRAP: GPIO46 must be LOW at reset. R108 10k to GND does that AND leaves the backlight
//   boost U17 disabled until firmware drives it
#define AQROOT_PIN_DISP_BL_PWM        46

// U1.17 IO9   /NFC_CS_N
//   ST25R3916 chip select, active low
#define AQROOT_PIN_NFC_CS_N           9

// U1.18 IO10  /DISP_CS_N
//   display chip select, active low
#define AQROOT_PIN_DISP_CS_N          10

// U1.19 IO11  /SPI_A_MOSI
//   shared SPI-A: display + microSD
#define AQROOT_PIN_SPI_A_MOSI         11

// U1.20 IO12  /SPI_A_SCK
//   shared SPI-A
#define AQROOT_PIN_SPI_A_SCK          12

// U1.21 IO13  /SPI_A_MISO
//   shared SPI-A -- reaches the microSD ONLY. R112 0R is DNP, so the display SDO is
//   ISOLATED and the panel CANNOT be read back
#define AQROOT_PIN_SPI_A_MISO         13

// U1.22 IO14  /DISP_DC
//   display data/command
#define AQROOT_PIN_DISP_DC            14

// U1.23 IO21  /WAKE_INT_N
//   shared open-drain wake line: U2./INT, U3./INT and the accessory attention path through
//   Q10. R3 10k pull-up. LEVEL sensitive, ACTIVE LOW, RTC-capable for deep-sleep wake
#define AQROOT_PIN_WAKE_INT_N         21

// U1.24 IO47  /NATIVE_B
//   Community Port native GPIO B, J5.8 through R62 100R, D2 ESD
#define AQROOT_PIN_NATIVE_B           47

// U1.25 IO48  /SD_CS_N
//   microSD chip select, active low
#define AQROOT_PIN_SD_CS_N            48

// U1.27 IO0   /02_MCU_CORE/BOOT_N
//   recessed BOOT/recovery button SW1; readable as a user button after boot, ACTIVE LOW
//   STRAP: GPIO0 download strap. R2 10k to +3V3; SW1 pulls it to GND
#define AQROOT_PIN_BOOT_N             0

// U1.31 IO38  /NATIVE_A
//   Community Port native GPIO A, J5.7 through R61 100R, D2 ESD
#define AQROOT_PIN_NATIVE_A           38

// U1.32 IO39  /I2S_BCLK
//   shared I2S bit clock: MAX98357A out + DMM-4026 mic in
#define AQROOT_PIN_I2S_BCLK           39

// U1.33 IO40  /I2S_LRCLK
//   shared I2S word clock
#define AQROOT_PIN_I2S_LRCLK          40

// U1.34 IO41  /I2S_SPK_DOUT
//   I2S data to the MAX98357A
#define AQROOT_PIN_I2S_SPK_DOUT       41

// U1.35 IO42  /I2S_MIC_DIN
//   I2S data from the DMM-4026-B-I2S MEMS microphone
#define AQROOT_PIN_I2S_MIC_DIN        42

// U1.36 RXD0  /IR_RX_GPIO44
//   TSOP38238 demodulated output, ACTIVE LOW, internally pulled up; Vs fed through R21 100R
//   + C11
#define AQROOT_PIN_IR_RX              44

// U1.37 TXD0  /02_MCU_CORE/UART0_TXD_DBG
//   debug UART TX to TP35 only -- there is NO USB-UART bridge; the console is the native
//   USB CDC
#define AQROOT_PIN_UART0_TXD          43

// U1.38 IO2   /I2C_SCL_INT
//   internal I2C clock, R20 2.2k pull-up
#define AQROOT_PIN_I2C_SCL            2

// U1.39 IO1   /I2C_SDA_INT
//   internal I2C data, R19 2.2k pull-up
#define AQROOT_PIN_I2C_SDA            1

// Pads with no firmware role, recorded so nothing reclaims them.
//   U1.3  EN    Net-(U1-EN)                                module EN / reset; RC only, no firmware access
//   U1.13 USB_D- /USB_D_MCU_N                               native USB D-, 22R series; owned by the USB Serial/JTAG peripheral
//   U1.14 USB_D+ /USB_D_MCU_P                               native USB D+, 22R series; owned by the USB Serial/JTAG peripheral
//   U1.26 IO45  /02_MCU_CORE/GPIO45_VDDSPI_STRAP           VDD_SPI strap -- NOT A FIRMWARE PIN
//   U1.28 IO35  (no net)                                   IO35 -- octal PSRAM, unusable, left NC
//   U1.29 IO36  (no net)                                   IO36 -- octal PSRAM, unusable, left NC
//   U1.30 IO37  (no net)                                   IO37 -- octal PSRAM, unusable, left NC

// ====================================================================================
// I2C -- internal bus
// ====================================================================================
#define AQROOT_I2C_SDA_GPIO 1
#define AQROOT_I2C_SCL_GPIO 2
// R19/R20 are 2.2k pull-ups.  Bring the bus up at 100 kHz, then verify 400 kHz.
#define AQROOT_I2C_BRINGUP_HZ  100000
#define AQROOT_I2C_RUN_HZ      400000

//   PCAL9535A, internal controls
#define AQROOT_I2C_ADDR_EXPANDER_U2    0x20

//   PCAL9535A, accessory + RGB
#define AQROOT_I2C_ADDR_EXPANDER_U3    0x21

//   MAX17048G+T10. ALRT (U14.5) reaches TP11 ONLY -- it is NOT wired to the MCU or to
//   either expander, so the gauge must be POLLED
#define AQROOT_I2C_ADDR_FUEL_GAUGE     0x36

//   BMI270. R118 0R to GND is FITTED and R119 is DNP, so SDO is low and the address is
//   0x68. INT1 arrives on GPIO3 through R18 220R
#define AQROOT_I2C_ADDR_IMU            0x68

//   FT6236-family on the display FPC. INT on U2.P06, RST on U2.P00
#define AQROOT_I2C_ADDR_TOUCH          0x38

// ====================================================================================
// PCAL9535A EXPANDERS -- bit map, direction, safe boot latch, mask, pull
// ====================================================================================
//
// Pins 4..11 are P00..P07 and pins 13..20 are P10..P17 on the PCAL9535APW.
// A bit index below is PORT*8 + BIT, so P00..P07 are 0..7 and P10..P17 are 8..15,
// which is the order the driver's 16-bit port words use.

// ---- U2 @ 0x20 -- internal controls, front buttons and internal status inputs
//      address strap: A0=GND, A1=GND, A2=GND
#define AQROOT_EXP_U2_ADDR 0x20

// U2 P00 (pad 4) /TOUCH_RST_N -- OUT, active LOW, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   capacitive touch controller reset, through J1.47. R12 100k to GND holds the panel in
//   reset until firmware releases it
#define AQROOT_U2_TOUCH_RST_N            0

// U2 P01 (pad 5) /SX1262_RST_N -- OUT, active LOW, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   E22/SX1262 reset. R13 100k to GND holds the LoRa module in reset at boot
#define AQROOT_U2_SX1262_RST_N           1

// U2 P02 (pad 6) /NFC_5V_EN -- OUT, active HIGH, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   U13 NFC 5 V boost enable. U13 IS DNP ON DEMO -- NFC runs from +3V3 through R106 0R --
//   so R14 100k to GND is the ONLY thing defining this node and firmware must never assert
//   it
#define AQROOT_U2_NFC_5V_EN              2

// U2 P03 (pad 7) /AMP_SD_MODE -- OUT, active HIGH, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   MAX98357A SD_MODE. R15 100k to GND = amplifier SHUT DOWN at boot. Driven to +3V3 the
//   part leaves shutdown and selects a SINGLE I2S slot (MAX98357A Table 1 top band); write
//   the mono sample into BOTH slots so the channel decision cannot silence the speaker
#define AQROOT_U2_AMP_SD_MODE            3

// U2 P04 (pad 8) /DISP_RST_N -- OUT, active LOW, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   display reset, through J1.10. R16 100k to GND holds the panel in reset at boot
#define AQROOT_U2_DISP_RST_N             4

// U2 P05 (pad 9) /SX1262_DIO1 -- IN, active HIGH, IRQ UNMASKED, internal pull NONE
//   LoRa interrupt, ROUTED at D-740 (U2.9 -> U8.13). The SX1262 drives DIO1 PUSH-PULL, so
//   the internal 100k must stay OFF -- a pull only fights it. The driver takes the
//   interrupt and does NOT poll GetIrqStatus()
#define AQROOT_U2_SX1262_DIO1            5

// U2 P06 (pad 10) /TOUCH_INT_N -- IN, active LOW, IRQ UNMASKED, internal pull UP
//   touch interrupt through J1.46. NOTHING ON THIS BOARD pulls this net -- the only other
//   pad is the display FPC -- so the internal 100k pull-up is REQUIRED: with the panel
//   unplugged an unmasked floating input would hold the shared wake line and starve the
//   buttons
#define AQROOT_U2_TOUCH_INT_N            6

// U2 P07 (pad 11) /SD_CARD_DETECT_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   microSD card detect, R113 100k pull-up
#define AQROOT_U2_SD_CARD_DETECT_N       7

// U2 P10 (pad 13) /08_BUTTONS_EXPANDERS/BTN_A_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   A / Select, SW6, R4 10k pull-up
#define AQROOT_U2_BTN_A_N                8

// U2 P11 (pad 14) /08_BUTTONS_EXPANDERS/BTN_UP_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   D-pad Up, R5 10k pull-up
#define AQROOT_U2_BTN_UP_N               9

// U2 P12 (pad 15) /08_BUTTONS_EXPANDERS/BTN_DOWN_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   D-pad Down, R6 10k pull-up
#define AQROOT_U2_BTN_DOWN_N             10

// U2 P13 (pad 16) /08_BUTTONS_EXPANDERS/BTN_LEFT_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   D-pad Left, R7 10k pull-up
#define AQROOT_U2_BTN_LEFT_N             11

// U2 P14 (pad 17) /08_BUTTONS_EXPANDERS/BTN_RIGHT_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   D-pad Right, R8 10k pull-up
#define AQROOT_U2_BTN_RIGHT_N            12

// U2 P15 (pad 18) /08_BUTTONS_EXPANDERS/BTN_B_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   B / Back, SW7, R9 10k pull-up
#define AQROOT_U2_BTN_B_N                13

// U2 P16 (pad 19) /BQ25185_STAT2 -- IN, active LOW, IRQ MASKED, internal pull NONE
//   charger STAT2. U2.19 is routed to R128/TP7 and reads a static HIGH, but U11.3 SHIPS
//   UNCONNECTED by owner decision D-742 -- the charger never drives it, so the bit carries
//   NO INFORMATION. MASKED, and firmware must not decode it
#define AQROOT_U2_BQ25185_STAT2          14

// U2 P17 (pad 20) /ACC_PWR_EN -- OUT, active HIGH, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   U16 TCA4307 Community-Port I2C buffer enable. R17 100k to GND keeps the accessory bus
//   isolated at boot
#define AQROOT_U2_ACC_PWR_EN             15

// ---- U3 @ 0x21 -- front RGB, accessory power tree and the two public XGPIO
//      address strap: A0=+3V3, A1=GND, A2=GND
#define AQROOT_EXP_U3_ADDR 0x21

// U3 P00 (pad 4) /08_BUTTONS_EXPANDERS/FRONT_RGB_R_N -- OUT, active LOW, IRQ MASKED, internal pull NONE, safe latch 1 (load_off)
//   D13 red cathode through R124 1k; anode is +3V3, so the LED is dark at 1 and dark again
//   while the expander is high-Z
#define AQROOT_U3_FRONT_RGB_R_N          0

// U3 P01 (pad 5) /08_BUTTONS_EXPANDERS/FRONT_RGB_G_N -- OUT, active LOW, IRQ MASKED, internal pull NONE, safe latch 1 (load_off)
//   D13 green cathode through R125 680R
#define AQROOT_U3_FRONT_RGB_G_N          1

// U3 P02 (pad 6) /08_BUTTONS_EXPANDERS/FRONT_RGB_B_N -- OUT, active LOW, IRQ MASKED, internal pull NONE, safe latch 1 (load_off)
//   D13 blue cathode through R126 390R
#define AQROOT_U3_FRONT_RGB_B_N          2

// U3 P03 (pad 7) /ACC_5V_SW_EN -- OUT, active HIGH, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   U22 TPS22950-Q1 5 V accessory load-switch ON. D-186 makes R131 100k to GND MANDATORY:
//   the TPS22950-Q1's internal 500k smart pull-down is not sufficient on its own and the
//   PCAL powers up high-impedance. This is the SECOND of D-186's two independent series
//   disconnects; the first is ACC_5V_BOOST_EN on U3.P13
#define AQROOT_U3_ACC_5V_SW_EN           3

// U3 P04 (pad 8) /XGPIO4 -- IN, active HIGH, IRQ MASKED, internal pull UP
//   public Community-Port expansion GPIO, J5.13 through R55 100R, D4 ESD. Boots as an INPUT
//   with the internal 100k pull-up so an empty header reads a defined 1. MASKED is MX-9: an
//   accessory must not be able to hold the shared wake line and starve the buttons
#define AQROOT_U3_XGPIO4                 4

// U3 P05 (pad 9) /XGPIO5 -- IN, active HIGH, IRQ MASKED, internal pull UP
//   public Community-Port expansion GPIO, J5.14 through R56 100R, D4 ESD. See XGPIO4
#define AQROOT_U3_XGPIO5                 5

// U3 P06 (pad 10) NC-DEMO -- IN, active HIGH, IRQ MASKED, internal pull UP
//   NC-DEMO spare. No external part at all, so the internal pull-up is what keeps a CMOS
//   input from floating
#define AQROOT_U3_SPARE_U3_P06           6

// U3 P07 (pad 11) NC-DEMO -- IN, active HIGH, IRQ MASKED, internal pull UP
//   NC-DEMO spare -- see SPARE_U3_P06
#define AQROOT_U3_SPARE_U3_P07           7

// U3 P10 (pad 13) NC-DEMO -- IN, active HIGH, IRQ MASKED, internal pull UP
//   NC-DEMO spare -- see SPARE_U3_P06
#define AQROOT_U3_SPARE_U3_P10           8

// U3 P11 (pad 14) NC-DEMO -- IN, active HIGH, IRQ MASKED, internal pull UP
//   NC-DEMO spare -- see SPARE_U3_P06
#define AQROOT_U3_SPARE_U3_P11           9

// U3 P12 (pad 15) /ACC_3V3_EN -- OUT, active HIGH, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   U20 TPS22950-Q1 switched 3.3 V accessory rail ON. R98 100k to GND
#define AQROOT_U3_ACC_3V3_EN             10

// U3 P13 (pad 16) /ACC_5V_BOOST_EN -- OUT, active HIGH, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   U21 TPS61023 5 V accessory boost ON. R102 100k to GND is MANDATORY per D-186. FIRST of
//   the two independent series disconnects; ACC_5V_SW_EN is the second, and the 5 V rail
//   requires BOTH
#define AQROOT_U3_ACC_5V_BOOST_EN        11

// U3 P14 (pad 17) /ACC_DETECT_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   accessory present at J5.21, R129 100k pull-up, R64 100R series, D5 ESD
#define AQROOT_U3_ACC_DETECT_N           12

// U3 P15 (pad 18) /ACC_POWER_FAULT_N -- IN, active LOW, IRQ UNMASKED, internal pull NONE
//   wire-OR fault flag from U20 and U22, R103 100k pull-up. A fault here must drop BOTH
//   accessory enables
#define AQROOT_U3_ACC_POWER_FAULT_N      13

// U3 P16 (pad 19) /SX1262_RXEN -- OUT, active HIGH, IRQ MASKED, internal pull NONE, safe latch 0 (external_pull)
//   E22 RF receive-path enable, R74 100k to GND. TXEN is NOT an MCU pin: U8.7/U8.8 are
//   driven by the SX1262's own DIO2, so firmware must enable DIO2-as-RF-switch
#define AQROOT_U3_SX1262_RXEN            14

// U3 P17 (pad 20) /BQ25185_STAT1 -- IN, active LOW, IRQ MASKED, internal pull NONE
//   charger STAT1, R127 10k pull-up. SLUSF65B Table 6-2: LOW = CHARGER FAULT, DIRECTLY
//   OBSERVED. HIGH is AMBIGUOUS between charging and complete because STAT2 is unconnected.
//   MASKED and POLLED rather than wired to the wake line: STAT1 only moves on fault
//   entry/exit, and the board carries no NTC (R38 10k to GND is SLUSF65B's own 'TS function
//   not required' network), so there is no temperature-boundary source of chatter to wake
//   on
#define AQROOT_U3_BQ25185_STAT1          15

// ====================================================================================
// AS-BUILT LIMITS -- facts firmware cannot discover and must not get wrong
// ====================================================================================

//   EVIDENCE: U11.3 carries /BQ25185_STAT2 and is UNROUTED (owner decision 2026-09-17,
//   D-742)
//   FIRMWARE: STAT1 LOW is a directly observed charger fault. STAT1 HIGH is AMBIGUOUS
//   between charging and charge-complete / sleep / disabled. D-776 CORRECTED WHAT THIS LINE
//   USED TO SAY: it named 'an INFERENCE from VBUS presence plus the MAX17048 trend', and
//   THERE IS NO VBUS-PRESENT SIGNAL ON THIS BOARD -- see AQROOT_VBUS_PRESENT_UNREADABLE.
//   The only input left is the MAX17048 voltage and SOC TREND, which is weak and slow. Do
//   not display a charging state; display state-of-charge.
#define AQROOT_CHARGER_STAT2_UNCONNECTED          1

//   EVIDENCE: R112 0R is DNP, so /03_SPI_A_DISPLAY_SD/DISP_SDO never reaches /SPI_A_MISO
//   FIRMWARE: The panel is WRITE-ONLY. Never read back a display register; SPI-A MISO
//   belongs to the microSD alone.
#define AQROOT_DISPLAY_SDO_ISOLATED               1

//   EVIDENCE: /01_POWER_TREE/MAX17048_ALRT_N reaches TP11 and U14.5 only
//   FIRMWARE: Poll the MAX17048. There is no alert interrupt path.
#define AQROOT_FUEL_GAUGE_ALRT_NOT_WIRED          1

//   EVIDENCE: /09_COMMUNITY_HEADER/TCA4307_READY reaches TP44 and U16.5 only
//   FIRMWARE: The accessory-bus READY flag is a bench probe, not a readable signal. Confirm
//   the accessory bus by addressing it.
#define AQROOT_ACC_BUS_READY_NOT_WIRED            1

//   EVIDENCE: R106 0R FIT ties /NFC_SUPPLY to +3V3; R107 and U13 are DNP
//   FIRMWARE: NFC runs from the 3.3 V path. Never assert NFC_5V_EN.
#define AQROOT_NFC_ON_3V3                         1

//   EVIDENCE: U8.7/U8.8 carry /04_SPI_B_RADIOS_NFC/DIO2_TXEN, which no MCU or expander pin
//   touches
//   FIRMWARE: Configure the SX1262 to drive DIO2 as the RF switch; only RXEN is under
//   firmware control (U3.P16).
#define AQROOT_SX1262_TXEN_IS_DIO2                1

//   EVIDENCE: only /CC1101_GDO0 leaves U7 to the MCU
//   FIRMWARE: Route every CC1101 status assertion through GDO0.
#define AQROOT_CC1101_GDO2_NOT_WIRED              1

//   EVIDENCE: MK1.6 and U5.16 both sit on /I2S_BCLK, and MK1.5 and U5.14 both sit on
//   /I2S_LRCLK -- one clock pair, two devices
//   FIRMWARE: ONE I2S peripheral must own BCLK and LRCLK. Running a second controller as a
//   master on the same pins puts two drivers on each clock. Use full-duplex master (TX to
//   U5, RX from MK1) in the application, or one direction at a time in bring-up.
#define AQROOT_I2S_CLOCKS_ARE_SHARED              1

//   EVIDENCE: U7, U8 and U9 share /SPI_B_SCK, /SPI_B_MOSI and /SPI_B_MISO
//   FIRMWARE: One transceiver transmits at a time; deselect the other two before any
//   transmit.
#define AQROOT_SHARED_SPI_B_ONE_TX                1

//   EVIDENCE: U11.6 TS/MR carries only R38 10k to GND -- SLUSF65B section 8.3.9's 'TS
//   function not required' network
//   FIRMWARE: The charger does not measure pack temperature. Do not report a battery
//   temperature, and do not expect TS faults.
#define AQROOT_NO_BATTERY_NTC                     1

// ====================================================================================
// PROBED BUT NOT READABLE -- computed off the copper, not remembered (D-776)
// ====================================================================================
//
// Every net below touches a TP pad and touches NO pad of U1, U2 or U3, so no
// firmware on this board can read it.  The LIST is derived from the board file;
// the generator REFUSES TO EMIT if a net in that set is undeclared, or if a
// declaration names a net that has since been wired.  Rails and analog nodes are
// accounted for in the generator and in the JSON; only SIGNALS appear here.

//   /01_POWER_TREE/BAT_PROT_SHDN_CTL  (probes: TP19.1)
//   the battery-protection SHDN control is driven by Q4/R83 from the autonomous recovery
//   logic and reaches TP19. It is neither readable nor firmware-drivable, by design --
//   protection must not depend on software.
#define AQROOT_BAT_PROT_SHDN_UNREADABLE           1

//   /01_POWER_TREE/LTC4368_FAULT_N  (probes: TP18.1)
//   the LTC4368's own FAULT output reaches R81 100k to +3V3, R82 1M to GND, TP18 and Q9's
//   GATE. Q9's drain is REC_FAULT_B, which goes to Q8 and R96 inside the autonomous
//   dead-cell recovery chain and to no readable pin. FIRMWARE CANNOT OBSERVE THAT THE
//   LATCHING BATTERY BREAKER HAS TRIPPED. On a trip the pack is disconnected and the board
//   runs only if VIN is present; do not report a battery-protection state, and do not
//   attribute a vanished battery to the gauge.
#define AQROOT_BREAKER_FAULT_UNREADABLE           1

//   /01_POWER_TREE/MAX17048_ALRT_N  (probes: TP11.1)
//   see AQROOT_FUEL_GAUGE_ALRT_NOT_WIRED -- U14.5 and TP11 only. Poll the gauge.
#define AQROOT_FUEL_GAUGE_ALRT_UNREADABLE         1

//   /01_POWER_TREE/VBUS_PRESENT  (probes: TP31.1)
//   R104 150k / R105 220k divide USB_VBUS_CHG to 2.973 V at VBUS 5.0 V, C68 filters it, and
//   the node reaches TP31 ONLY -- no MCU pin and no expander bit. THERE IS NO USB-PRESENT
//   SIGNAL ON THIS REVISION. Do not infer 'charging' from VBUS: the native USB CDC link
//   detects a USB HOST, not a charger, and a dumb 5 V supply charges this board invisibly.
//   D-776 measured the fix and deferred it: the divider must MOVE beside U3 (USB_VBUS_CHG
//   already runs within ~3 mm of U3's west column) and land on U3 P06; hauling it from
//   where it sits is NO_PATH at 0.200 mm on all three routable layers at both 0.10 and 0.05
//   mm lattices.
#define AQROOT_VBUS_PRESENT_UNREADABLE            1

//   /03_SPI_A_DISPLAY_SD/DISP_SDO  (probes: TP36.1)
//   see AQROOT_DISPLAY_SDO_ISOLATED -- R112 0R is DNP, so the panel's SDO reaches J1 and
//   TP36 only.
#define AQROOT_DISPLAY_SDO_UNREADABLE             1

//   /09_COMMUNITY_HEADER/TCA4307_READY  (probes: TP44.1)
//   see AQROOT_ACC_BUS_READY_NOT_WIRED -- U16.5, R46 and TP44 only. Confirm the accessory
//   bus by addressing it.
#define AQROOT_ACC_BUS_READY_UNREADABLE           1

//   Net-(U12-PG)  (probes: TP8.1)
//   the TPS63020's POWER GOOD reaches R41 1M to +3V3 and TP8 only. There is no main-rail
//   power-good input. A +3V3 droop is not observable; the MCU's own brown-out is the only
//   indication.
#define AQROOT_MAIN_RAIL_PG_UNREADABLE            1

// ====================================================================================
// RAILS AND ANALOG NODES also probed and unreadable, listed so the computed set
// above is fully accounted for.  No #define: firmware has no use for them.
// ====================================================================================
//   /01_POWER_TREE/ACC_5V_RAW                      rail    boost output ahead of U22
//   /01_POWER_TREE/BAT_CONNECTOR_P                 rail    J4 pack terminal ahead of F1
//   /01_POWER_TREE/BAT_PROTECTED_P                 rail    the pack rail the MAX17048 measures
//   /01_POWER_TREE/BAT_RAW                         rail    pack rail ahead of the protection FETs
//   /01_POWER_TREE/BAT_SENSE                       analog  LTC4368 Kelvin sense node across R75
//   /01_POWER_TREE/LTC_GATE                        analog  LTC4368 gate drive to Q2/Q3
//   /01_POWER_TREE/NFC_5V_PA_PENDING               rail    the DNP 5 V NFC PA rail
//   /01_POWER_TREE/N_POL                           analog  U19 comparator input in the dead-cell recovery divider
//   /01_POWER_TREE/REC_DIODE_IN                    analog  dead-cell recovery steering node at D12/R95
//   /01_POWER_TREE/REC_GATE_N                      analog  dead-cell recovery gate drive at Q5/Q6/R94
//   /01_POWER_TREE/REF_POL                         analog  U19 comparator reference in the dead-cell recovery divider
//   /04_SPI_B_RADIOS_NFC/NFC_ANT_A                 analog  NFC antenna terminal
//   /04_SPI_B_RADIOS_NFC/NFC_ANT_B                 analog  NFC antenna terminal
//   /07_IR/IR_LED_A                                analog  IR LED anode, driven by Q1
//   /09_COMMUNITY_HEADER/ACC_DETECT_N_HDR          analog  the header side of ACC_DETECT_N
//   /09_COMMUNITY_HEADER/EXT_SCL                   rail    accessory-side I2C clock
//   /09_COMMUNITY_HEADER/EXT_SDA                   rail    accessory-side I2C data
//   /ACC_3V3_SW                                    rail    switched accessory 3.3 V rail
//   /ACC_5V_SW                                     rail    switched accessory 5 V rail
//   /NFC_SUPPLY                                    rail    the NFC front end's supply
//   Net-(SW9-A)                                    analog  the SW9 physical power switch's EN network into U12
