M48
; DRILL file KiCad 10.0.3 date 2026-08-20T19:01:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-20T19:01:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X71.5Y-7.79
T2
X32.11Y-148.72
X37.89Y-148.72
T3
X3.1Y-59.5
X9.9Y-59.5
M30
